<?php

/**
 * @file
 * This is the module to create the Related media component.
 * o	Media announcement o	Brochure o	White paper

 */
function cgi_related_media_theme($existing, $type, $theme, $path) {
    return [
      'media_overview_page' => [
        'variables' => [
          'mediaAnnouncement' => null,
          'brochure' => null,
          'whitePaper' => null,
          'blogFeed' => null,
        ]
      ],
    ];
  }